CREATE USER cbayconnect
IDENTIFIED BY cbayconnectpassword;

GRANT DBA TO cbayconnect;

DROP TABLE MESSAGE;

DROP TABLE IMAGE;
DROP TABLE RATING;
DROP TABLE ORDERS;
DROP TABLE ITEM;
DROP TABLE CLIENT;


CREATE TABLE CLIENT
(
    UserID NUMBER(6) NOT NULL,
    FirstName VARCHAR2(20) NOT NULL,
    LastName VARCHAR2(20) NOT NULL,
    UserType VARCHAR2(30),
    UserName VARCHAR2(24) UNIQUE,
    PW VARCHAR2(60),
    Email VARCHAR2(60) UNIQUE,
    RatingAvg NUMBER(6),
    CONSTRAINT PK_USER PRIMARY KEY  (UserID)
);

CREATE TABLE ITEM
(
    ItemID NUMBER(6) NOT NULL,
    UserID NUMBER(6) NOT NULL,
    ItemName VARCHAR2(20) NOT NULL,
    Description VARCHAR2(20) NOT NULL,
    Price NUMBER(6),
    RatingAvg NUMBER(5),
    Phone VARCHAR2(24),
    Email VARCHAR2(60),
    CONSTRAINT PK_ITEM PRIMARY KEY  (ItemID),
    CONSTRAINT FK_OWNER FOREIGN KEY (UserID) 
    REFERENCES CLIENT (UserID)  ON DELETE CASCADE
    
);

CREATE TABLE ORDERS
(
    TransactionID NUMBER(6) NOT NULL,
    OrderID NUMBER(6),
    ItemID NUMBER(6),
    UserID NUMBER(6),
    Status VARCHAR2(20) NOT NULL,
    PW VARCHAR2(20),
    CONSTRAINT PK_TRANSACTION PRIMARY KEY  (TransactionID),
    CONSTRAINT FK_ITEM_IN_ORDER FOREIGN KEY (ItemID) 
    REFERENCES ITEM (ItemID)  ON DELETE CASCADE,
    CONSTRAINT FK_BUYER_IN_ORDER FOREIGN KEY (UserID) 
    REFERENCES CLIENT (UserID)  ON DELETE CASCADE
);

CREATE TABLE RATING
(
    RatingID NUMBER(9) NOT NULL,
    UserID NUMBER(9),
    ItemID NUMBER(9),
    TextRatingItem VARCHAR2(240) NOT NULL,
    NumRatingItem NUMBER(6) NOT NULL,
    CONSTRAINT PK_RATING PRIMARY KEY  (RatingID),
    CONSTRAINT FK_ITEM_IN_RATING FOREIGN KEY (ItemID) 
    REFERENCES ITEM (ItemID)  ON DELETE CASCADE,
    CONSTRAINT FK_SELLER_IN_RATING FOREIGN KEY (UserID) 
    REFERENCES CLIENT (UserID)  ON DELETE CASCADE
    
);

CREATE TABLE MESSAGE
(
    MessageID NUMBER(6) NOT NULL,
    ThreadID NUMBER(4) UNIQUE,
    TransactionID NUMBER(6) NOT NULL,
    SenderID NUMBER(6) NOT NULL,
    ResponderID NUMBER(6) NOT NULL,
    MessageContent VARCHAR2(240),
    Subject VARCHAR2(100),
    CONSTRAINT PK_MESSAGE PRIMARY KEY  (MessageID),
    CONSTRAINT FK_TRANSACTION_IN_MESSAGE FOREIGN KEY (TransactionID) 
    REFERENCES ORDERS (TransactionID)  ON DELETE CASCADE,
    CONSTRAINT FK_SENDER_IN_MESSAGE FOREIGN KEY (SenderID) 
    REFERENCES CLIENT (UserID)  ON DELETE CASCADE,
    CONSTRAINT FK_RESPONDER_IN_MESSAGE FOREIGN KEY (ResponderID) 
    REFERENCES CLIENT (UserID)  ON DELETE CASCADE
    
);

CREATE TABLE IMAGE
(
    ImageID NUMBER(6) NOT NULL,
    ItemID NUMBER(6) NOT NULL,
    Image Blob,
    FileName VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_IMAGE PRIMARY KEY  (ImageID),
    CONSTRAINT FK_ITEM_IN_IMAGE FOREIGN KEY (ItemID) 
    REFERENCES ITEM (ItemID)  ON DELETE CASCADE
);



-----------------------------------------------------------------------------------------------


DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ
    start with 10000
    increment by 1;


DROP SEQUENCE ITEM_ID_SEQ;
CREATE SEQUENCE ITEM_ID_SEQ
    start with 20000
    increment by 1;

DROP SEQUENCE TRANS_ID_SEQ;
CREATE SEQUENCE TRANS_ID_SEQ
    start with 30000
    increment by 1;

DROP SEQUENCE ORDER_ID_SEQ;
CREATE SEQUENCE ORDER_ID_SEQ
    start with 40000
    increment by 1;

DROP SEQUENCE MESSAGE_ID_SEQ;
CREATE SEQUENCE MESSAGE_ID_SEQ
    start with 50000
    increment by 1;

DROP SEQUENCE IMAGE_ID_SEQ;
CREATE SEQUENCE IMAGE_ID_SEQ
    start with 60000
    increment by 1;
    
DROP SEQUENCE RATING_ID_SEQ;
CREATE SEQUENCE RATING_ID_SEQ
    start with 70000
    increment by 1;
    





